---
database:
  url: postgres://app:app@postgres-app:5432/app?sslmode=disable

healthcheck:
  healthBind: ":8080"

logging:
  level: info  # "debug", "info", "warn", "error"

temporal:
  address: temporal:7233
  namespace: default
  taskQueue: ggwd-task-queue
  # FIXME: auth

geoguessrApi:
  baseUrl: https://www.geoguessr.com/api
  cookie: cookie
  proxy: http://gluetun:8888  # or leave empty for no proxy
  timeoutSeconds: 30
  cache:
    enabled: true
    cachePath: /tmp/ggwd_cache

notifierApi:
  shoutrrr: []  # see https://containrrr.dev/shoutrrr/v0.8/services/discord/
  #  - "discord://webhook_token@webhook_id"

watchdogs:
  CompetitiveMaps:
    enabled: true
    scheduleFrequencyHours: 6
    notifyAbout:
      - divisionName: "Master I"
        gameMode: "standardDuels"  # "standardDuels", "noMoveDuels", "nmpzDuels"
    ignoreMapChanges:
      boundsChanges: true
      maxErrDistanceChanges: true
      locationCountChanges: false
      updatedAtChanges: false
    temporalAdvanced:
      workflowName: "GGWDCompetitiveMapsWorkflow"
      fanoutActivity:
        startToCloseTimeoutSeconds: 60
        retryInitialIntervalSeconds: 5
        retryBackoffCoefficient: 2
        retryMaximumIntervalSeconds: 60
        retryMaximumAttempts: 5
      parallelism: 2
  UserStats:
    enabled: true
    scheduleDaily:  # UTC time
      hour: 4
      minute: 0
    observeUsers:
      - user_id  # user ID, not login
    temporalAdvanced:
      workflowName: "GGWDUserStatsWorkflow"
      fanoutActivity:
        startToCloseTimeoutSeconds: 60
        retryInitialIntervalSeconds: 5
        retryBackoffCoefficient: 2
        retryMaximumIntervalSeconds: 60
        retryMaximumAttempts: 5
      parallelism: 2

preflight:
  ipInfoCheckUrl: https://api.ipify.org?format=json
  ipInfoCheckEnabled: true
