---
services:
  gluetun:
    image: qmcgaw/gluetun
    cap_add:
      - NET_ADMIN
    env_file:
      - ./vpn.env
    devices:
      - /dev/net/tun:/dev/net/tun
    environment:
      - HTTPPROXY=on
      - HTTPPROXY_LOG=on
    ports:
      - "8888:8888"

  fetcher:
    build: .
    # network_mode: "service:gluetun"
    depends_on:
      gluetun:
        condition: service_healthy
    env_file:
      - ./app.env
    environment:
      - HTTP_PROXY_URL=http://gluetun:8888
    restart: no
